development:
  secret_key_base: SECRET_KEY_HERE

test:
  secret_key_base: SECRET_KEY_HERE

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>